### PR TITLE
chore: new flag export only header bytes

### PR DESCRIPTION
**Pull request by RafilxTenfen**
Created new structure to avoid exporting `params: []` empty as it was before by using the `bbnbtclightclienttypes.GenState` as before

Add new flag `with-height` to `btc-headers` command

### CODE REVIEW

**Comment by gitferry** [comment]
From https://github.com/babylonlabs-io/babylon/pull/4, I understand that we do not want `work` in the output right? Why not just remove it other than have a flag?

**Comment by RafilxTenfen** [comment]
integration tests pass locally

**Comment by RafilxTenfen** [comment]
> From [babylonlabs-io/babylon#4](https://github.com/babylonlabs-io/babylon/pull/4), I understand that we do not want `work` in the output right? Why not just remove it other than have a flag?

Well, I thought since it was already done I left the option to export all fields and we could use to confirm some values if needed, but if you prefer to remove it I can remove it entirely @gitferry

**Review by gitferry — COMMENTED** [review]
Let's remove `work` entirely as the calculation should be done in Babylon side. We can also remove `hash` as this can be obtained from the bytes. This leaves height and bytes. If we want to keep the option of having `height`, maybe we can have a flag called `with-height` other than `only-header-bytes`. This way, for preparing upgrade, we don't need to specify any flag

**Review by gitferry — APPROVED** [review]
Code-wise lgtm, not sure why e2e failed though

**Comment by gitferry** [comment]
CI fixed in #14

**Review by KonradStaniec — APPROVED** [review]

**Pull request merged**
